/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// LfCreateChatPromptRequest
    /// </summary>
    [DataContract(Name = "CreateChatPromptRequest")]
    public partial class LfCreateChatPromptRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LfCreateChatPromptRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LfCreateChatPromptRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LfCreateChatPromptRequest" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="prompt">prompt (required).</param>
        /// <param name="config">config.</param>
        /// <param name="labels">List of deployment labels of this prompt version..</param>
        /// <param name="tags">List of tags to apply to all versions of this prompt..</param>
        /// <param name="commitMessage">Commit message for this prompt version..</param>
        public LfCreateChatPromptRequest(string name = default, List<LfChatMessageWithPlaceholders> prompt = default, Object config = default, List<string> labels = default, List<string> tags = default, string commitMessage = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for LfCreateChatPromptRequest and cannot be null");
            }
            this.Name = name;
            // to ensure "prompt" is required (not null)
            if (prompt == null)
            {
                throw new ArgumentNullException("prompt is a required property for LfCreateChatPromptRequest and cannot be null");
            }
            this.Prompt = prompt;
            this.Config = config;
            this.Labels = labels;
            this.Tags = tags;
            this.CommitMessage = commitMessage;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Prompt
        /// </summary>
        [DataMember(Name = "prompt", IsRequired = true, EmitDefaultValue = true)]
        public List<LfChatMessageWithPlaceholders> Prompt { get; set; }

        /// <summary>
        /// Gets or Sets Config
        /// </summary>
        [DataMember(Name = "config", EmitDefaultValue = true)]
        public Object Config { get; set; }

        /// <summary>
        /// List of deployment labels of this prompt version.
        /// </summary>
        /// <value>List of deployment labels of this prompt version.</value>
        [DataMember(Name = "labels", EmitDefaultValue = true)]
        public List<string> Labels { get; set; }

        /// <summary>
        /// List of tags to apply to all versions of this prompt.
        /// </summary>
        /// <value>List of tags to apply to all versions of this prompt.</value>
        [DataMember(Name = "tags", EmitDefaultValue = true)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Commit message for this prompt version.
        /// </summary>
        /// <value>Commit message for this prompt version.</value>
        [DataMember(Name = "commitMessage", EmitDefaultValue = true)]
        public string CommitMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LfCreateChatPromptRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("  Config: ").Append(Config).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  CommitMessage: ").Append(CommitMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
