/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// LfCreateScoreRequest
    /// </summary>
    [DataContract(Name = "CreateScoreRequest")]
    public partial class LfCreateScoreRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets DataType
        /// </summary>
        [DataMember(Name = "dataType", EmitDefaultValue = false)]
        public LfScoreDataType? DataType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LfCreateScoreRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LfCreateScoreRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LfCreateScoreRequest" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="traceId">traceId.</param>
        /// <param name="sessionId">sessionId.</param>
        /// <param name="observationId">observationId.</param>
        /// <param name="datasetRunId">datasetRunId.</param>
        /// <param name="name">name (required).</param>
        /// <param name="value">value (required).</param>
        /// <param name="comment">comment.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="varEnvironment">The environment of the score. Can be any lowercase alphanumeric string with hyphens and underscores that does not start with &#39;langfuse&#39;..</param>
        /// <param name="dataType">dataType.</param>
        /// <param name="configId">Reference a score config on a score. The unique langfuse identifier of a score config. When passing this field, the dataType and stringValue fields are automatically populated..</param>
        public LfCreateScoreRequest(string id = default, string traceId = default, string sessionId = default, string observationId = default, string datasetRunId = default, string name = default, LfCreateScoreValue value = default, string comment = default, Object metadata = default, string varEnvironment = default, LfScoreDataType? dataType = default, string configId = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for LfCreateScoreRequest and cannot be null");
            }
            this.Name = name;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for LfCreateScoreRequest and cannot be null");
            }
            this.Value = value;
            this.Id = id;
            this.TraceId = traceId;
            this.SessionId = sessionId;
            this.ObservationId = observationId;
            this.DatasetRunId = datasetRunId;
            this.Comment = comment;
            this.Metadata = metadata;
            this.VarEnvironment = varEnvironment;
            this.DataType = dataType;
            this.ConfigId = configId;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets TraceId
        /// </summary>
        [DataMember(Name = "traceId", EmitDefaultValue = true)]
        public string TraceId { get; set; }

        /// <summary>
        /// Gets or Sets SessionId
        /// </summary>
        [DataMember(Name = "sessionId", EmitDefaultValue = true)]
        public string SessionId { get; set; }

        /// <summary>
        /// Gets or Sets ObservationId
        /// </summary>
        [DataMember(Name = "observationId", EmitDefaultValue = true)]
        public string ObservationId { get; set; }

        /// <summary>
        /// Gets or Sets DatasetRunId
        /// </summary>
        [DataMember(Name = "datasetRunId", EmitDefaultValue = true)]
        public string DatasetRunId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /*
        <example>novelty</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public LfCreateScoreValue Value { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name = "comment", EmitDefaultValue = true)]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Object Metadata { get; set; }

        /// <summary>
        /// The environment of the score. Can be any lowercase alphanumeric string with hyphens and underscores that does not start with &#39;langfuse&#39;.
        /// </summary>
        /// <value>The environment of the score. Can be any lowercase alphanumeric string with hyphens and underscores that does not start with &#39;langfuse&#39;.</value>
        [DataMember(Name = "environment", EmitDefaultValue = true)]
        public string VarEnvironment { get; set; }

        /// <summary>
        /// Reference a score config on a score. The unique langfuse identifier of a score config. When passing this field, the dataType and stringValue fields are automatically populated.
        /// </summary>
        /// <value>Reference a score config on a score. The unique langfuse identifier of a score config. When passing this field, the dataType and stringValue fields are automatically populated.</value>
        [DataMember(Name = "configId", EmitDefaultValue = true)]
        public string ConfigId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LfCreateScoreRequest {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TraceId: ").Append(TraceId).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  ObservationId: ").Append(ObservationId).Append("\n");
            sb.Append("  DatasetRunId: ").Append(DatasetRunId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  VarEnvironment: ").Append(VarEnvironment).Append("\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  ConfigId: ").Append(ConfigId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
