/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// LfCreateDatasetItemRequest
    /// </summary>
    [DataContract(Name = "CreateDatasetItemRequest")]
    public partial class LfCreateDatasetItemRequest : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public LfDatasetStatus? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LfCreateDatasetItemRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LfCreateDatasetItemRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LfCreateDatasetItemRequest" /> class.
        /// </summary>
        /// <param name="datasetName">datasetName (required).</param>
        /// <param name="input">input.</param>
        /// <param name="expectedOutput">expectedOutput.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="sourceTraceId">sourceTraceId.</param>
        /// <param name="sourceObservationId">sourceObservationId.</param>
        /// <param name="id">Dataset items are upserted on their id. Id needs to be unique (project-level) and cannot be reused across datasets..</param>
        /// <param name="status">status.</param>
        public LfCreateDatasetItemRequest(string datasetName = default, Object input = default, Object expectedOutput = default, Object metadata = default, string sourceTraceId = default, string sourceObservationId = default, string id = default, LfDatasetStatus? status = default)
        {
            // to ensure "datasetName" is required (not null)
            if (datasetName == null)
            {
                throw new ArgumentNullException("datasetName is a required property for LfCreateDatasetItemRequest and cannot be null");
            }
            this.DatasetName = datasetName;
            this.Input = input;
            this.ExpectedOutput = expectedOutput;
            this.Metadata = metadata;
            this.SourceTraceId = sourceTraceId;
            this.SourceObservationId = sourceObservationId;
            this.Id = id;
            this.Status = status;
        }

        /// <summary>
        /// Gets or Sets DatasetName
        /// </summary>
        [DataMember(Name = "datasetName", IsRequired = true, EmitDefaultValue = true)]
        public string DatasetName { get; set; }

        /// <summary>
        /// Gets or Sets Input
        /// </summary>
        [DataMember(Name = "input", EmitDefaultValue = true)]
        public Object Input { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedOutput
        /// </summary>
        [DataMember(Name = "expectedOutput", EmitDefaultValue = true)]
        public Object ExpectedOutput { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Gets or Sets SourceTraceId
        /// </summary>
        [DataMember(Name = "sourceTraceId", EmitDefaultValue = true)]
        public string SourceTraceId { get; set; }

        /// <summary>
        /// Gets or Sets SourceObservationId
        /// </summary>
        [DataMember(Name = "sourceObservationId", EmitDefaultValue = true)]
        public string SourceObservationId { get; set; }

        /// <summary>
        /// Dataset items are upserted on their id. Id needs to be unique (project-level) and cannot be reused across datasets.
        /// </summary>
        /// <value>Dataset items are upserted on their id. Id needs to be unique (project-level) and cannot be reused across datasets.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LfCreateDatasetItemRequest {\n");
            sb.Append("  DatasetName: ").Append(DatasetName).Append("\n");
            sb.Append("  Input: ").Append(Input).Append("\n");
            sb.Append("  ExpectedOutput: ").Append(ExpectedOutput).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  SourceTraceId: ").Append(SourceTraceId).Append("\n");
            sb.Append("  SourceObservationId: ").Append(SourceObservationId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
