/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// LfDatasetRunWithItems
    /// </summary>
    [DataContract(Name = "DatasetRunWithItems")]
    public partial class LfDatasetRunWithItems : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LfDatasetRunWithItems" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LfDatasetRunWithItems() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LfDatasetRunWithItems" /> class.
        /// </summary>
        /// <param name="id">Unique identifier of the dataset run (required).</param>
        /// <param name="name">Name of the dataset run (required).</param>
        /// <param name="description">Description of the run.</param>
        /// <param name="metadata">Metadata of the dataset run.</param>
        /// <param name="datasetId">Id of the associated dataset (required).</param>
        /// <param name="datasetName">Name of the associated dataset (required).</param>
        /// <param name="createdAt">The date and time when the dataset run was created (required).</param>
        /// <param name="updatedAt">The date and time when the dataset run was last updated (required).</param>
        /// <param name="datasetRunItems">datasetRunItems (required).</param>
        public LfDatasetRunWithItems(string id = default, string name = default, string description = default, Object metadata = default, string datasetId = default, string datasetName = default, DateTime createdAt = default, DateTime updatedAt = default, List<LfDatasetRunItem> datasetRunItems = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for LfDatasetRunWithItems and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for LfDatasetRunWithItems and cannot be null");
            }
            this.Name = name;
            // to ensure "datasetId" is required (not null)
            if (datasetId == null)
            {
                throw new ArgumentNullException("datasetId is a required property for LfDatasetRunWithItems and cannot be null");
            }
            this.DatasetId = datasetId;
            // to ensure "datasetName" is required (not null)
            if (datasetName == null)
            {
                throw new ArgumentNullException("datasetName is a required property for LfDatasetRunWithItems and cannot be null");
            }
            this.DatasetName = datasetName;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            // to ensure "datasetRunItems" is required (not null)
            if (datasetRunItems == null)
            {
                throw new ArgumentNullException("datasetRunItems is a required property for LfDatasetRunWithItems and cannot be null");
            }
            this.DatasetRunItems = datasetRunItems;
            this.Description = description;
            this.Metadata = metadata;
        }

        /// <summary>
        /// Unique identifier of the dataset run
        /// </summary>
        /// <value>Unique identifier of the dataset run</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Name of the dataset run
        /// </summary>
        /// <value>Name of the dataset run</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Description of the run
        /// </summary>
        /// <value>Description of the run</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Metadata of the dataset run
        /// </summary>
        /// <value>Metadata of the dataset run</value>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Id of the associated dataset
        /// </summary>
        /// <value>Id of the associated dataset</value>
        [DataMember(Name = "datasetId", IsRequired = true, EmitDefaultValue = true)]
        public string DatasetId { get; set; }

        /// <summary>
        /// Name of the associated dataset
        /// </summary>
        /// <value>Name of the associated dataset</value>
        [DataMember(Name = "datasetName", IsRequired = true, EmitDefaultValue = true)]
        public string DatasetName { get; set; }

        /// <summary>
        /// The date and time when the dataset run was created
        /// </summary>
        /// <value>The date and time when the dataset run was created</value>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// The date and time when the dataset run was last updated
        /// </summary>
        /// <value>The date and time when the dataset run was last updated</value>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets DatasetRunItems
        /// </summary>
        [DataMember(Name = "datasetRunItems", IsRequired = true, EmitDefaultValue = true)]
        public List<LfDatasetRunItem> DatasetRunItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LfDatasetRunWithItems {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  DatasetId: ").Append(DatasetId).Append("\n");
            sb.Append("  DatasetName: ").Append(DatasetName).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  DatasetRunItems: ").Append(DatasetRunItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
