/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// LfMembershipsResponse
    /// </summary>
    [DataContract(Name = "MembershipsResponse")]
    public partial class LfMembershipsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LfMembershipsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LfMembershipsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LfMembershipsResponse" /> class.
        /// </summary>
        /// <param name="memberships">memberships (required).</param>
        public LfMembershipsResponse(List<LfMembershipResponse> memberships = default)
        {
            // to ensure "memberships" is required (not null)
            if (memberships == null)
            {
                throw new ArgumentNullException("memberships is a required property for LfMembershipsResponse and cannot be null");
            }
            this.Memberships = memberships;
        }

        /// <summary>
        /// Gets or Sets Memberships
        /// </summary>
        [DataMember(Name = "memberships", IsRequired = true, EmitDefaultValue = true)]
        public List<LfMembershipResponse> Memberships { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LfMembershipsResponse {\n");
            sb.Append("  Memberships: ").Append(Memberships).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
