/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// Defines MembershipRole
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LfMembershipRole
    {
        /// <summary>
        /// Enum OWNER for value: OWNER
        /// </summary>
        [EnumMember(Value = "OWNER")]
        OWNER = 1,

        /// <summary>
        /// Enum ADMIN for value: ADMIN
        /// </summary>
        [EnumMember(Value = "ADMIN")]
        ADMIN = 2,

        /// <summary>
        /// Enum MEMBER for value: MEMBER
        /// </summary>
        [EnumMember(Value = "MEMBER")]
        MEMBER = 3,

        /// <summary>
        /// Enum VIEWER for value: VIEWER
        /// </summary>
        [EnumMember(Value = "VIEWER")]
        VIEWER = 4
    }

}
