/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// Defines ObservationType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LfObservationType
    {
        /// <summary>
        /// Enum SPAN for value: SPAN
        /// </summary>
        [EnumMember(Value = "SPAN")]
        SPAN = 1,

        /// <summary>
        /// Enum GENERATION for value: GENERATION
        /// </summary>
        [EnumMember(Value = "GENERATION")]
        GENERATION = 2,

        /// <summary>
        /// Enum EVENT for value: EVENT
        /// </summary>
        [EnumMember(Value = "EVENT")]
        EVENT = 3,

        /// <summary>
        /// Enum AGENT for value: AGENT
        /// </summary>
        [EnumMember(Value = "AGENT")]
        AGENT = 4,

        /// <summary>
        /// Enum TOOL for value: TOOL
        /// </summary>
        [EnumMember(Value = "TOOL")]
        TOOL = 5,

        /// <summary>
        /// Enum CHAIN for value: CHAIN
        /// </summary>
        [EnumMember(Value = "CHAIN")]
        CHAIN = 6,

        /// <summary>
        /// Enum RETRIEVER for value: RETRIEVER
        /// </summary>
        [EnumMember(Value = "RETRIEVER")]
        RETRIEVER = 7,

        /// <summary>
        /// Enum EVALUATOR for value: EVALUATOR
        /// </summary>
        [EnumMember(Value = "EVALUATOR")]
        EVALUATOR = 8,

        /// <summary>
        /// Enum EMBEDDING for value: EMBEDDING
        /// </summary>
        [EnumMember(Value = "EMBEDDING")]
        EMBEDDING = 9,

        /// <summary>
        /// Enum GUARDRAIL for value: GUARDRAIL
        /// </summary>
        [EnumMember(Value = "GUARDRAIL")]
        GUARDRAIL = 10
    }

}
