/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// Usage interface of OpenAI for improved compatibility.
    /// </summary>
    [DataContract(Name = "OpenAIUsage")]
    public partial class LfOpenAIUsage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LfOpenAIUsage" /> class.
        /// </summary>
        /// <param name="promptTokens">promptTokens.</param>
        /// <param name="completionTokens">completionTokens.</param>
        /// <param name="totalTokens">totalTokens.</param>
        public LfOpenAIUsage(int? promptTokens = default, int? completionTokens = default, int? totalTokens = default)
        {
            this.PromptTokens = promptTokens;
            this.CompletionTokens = completionTokens;
            this.TotalTokens = totalTokens;
        }

        /// <summary>
        /// Gets or Sets PromptTokens
        /// </summary>
        [DataMember(Name = "promptTokens", EmitDefaultValue = true)]
        public int? PromptTokens { get; set; }

        /// <summary>
        /// Gets or Sets CompletionTokens
        /// </summary>
        [DataMember(Name = "completionTokens", EmitDefaultValue = true)]
        public int? CompletionTokens { get; set; }

        /// <summary>
        /// Gets or Sets TotalTokens
        /// </summary>
        [DataMember(Name = "totalTokens", EmitDefaultValue = true)]
        public int? TotalTokens { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LfOpenAIUsage {\n");
            sb.Append("  PromptTokens: ").Append(PromptTokens).Append("\n");
            sb.Append("  CompletionTokens: ").Append(CompletionTokens).Append("\n");
            sb.Append("  TotalTokens: ").Append(TotalTokens).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
