/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// LfScoreV1
    /// </summary>
    [JsonConverter(typeof(LfScoreV1JsonConverter))]
    [DataContract(Name = "ScoreV1")]
    public partial class LfScoreV1 : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LfScoreV1" /> class
        /// with the <see cref="LfScoreV1OneOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of LfScoreV1OneOf.</param>
        public LfScoreV1(LfScoreV1OneOf actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LfScoreV1" /> class
        /// with the <see cref="LfScoreV1OneOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of LfScoreV1OneOf1.</param>
        public LfScoreV1(LfScoreV1OneOf1 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LfScoreV1" /> class
        /// with the <see cref="LfScoreV1OneOf2" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of LfScoreV1OneOf2.</param>
        public LfScoreV1(LfScoreV1OneOf2 actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(LfScoreV1OneOf) || value is LfScoreV1OneOf)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(LfScoreV1OneOf1) || value is LfScoreV1OneOf1)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(LfScoreV1OneOf2) || value is LfScoreV1OneOf2)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: LfScoreV1OneOf, LfScoreV1OneOf1, LfScoreV1OneOf2");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `LfScoreV1OneOf`. If the actual instance is not `LfScoreV1OneOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of LfScoreV1OneOf</returns>
        public LfScoreV1OneOf GetLfScoreV1OneOf()
        {
            return (LfScoreV1OneOf)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `LfScoreV1OneOf1`. If the actual instance is not `LfScoreV1OneOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of LfScoreV1OneOf1</returns>
        public LfScoreV1OneOf1 GetLfScoreV1OneOf1()
        {
            return (LfScoreV1OneOf1)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `LfScoreV1OneOf2`. If the actual instance is not `LfScoreV1OneOf2`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of LfScoreV1OneOf2</returns>
        public LfScoreV1OneOf2 GetLfScoreV1OneOf2()
        {
            return (LfScoreV1OneOf2)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LfScoreV1 {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, LfScoreV1.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of LfScoreV1
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of LfScoreV1</returns>
        public static LfScoreV1 FromJson(string jsonString)
        {
            LfScoreV1 newLfScoreV1 = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newLfScoreV1;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(LfScoreV1OneOf).GetProperty("AdditionalProperties") == null)
                {
                    newLfScoreV1 = new LfScoreV1(JsonConvert.DeserializeObject<LfScoreV1OneOf>(jsonString, LfScoreV1.SerializerSettings));
                }
                else
                {
                    newLfScoreV1 = new LfScoreV1(JsonConvert.DeserializeObject<LfScoreV1OneOf>(jsonString, LfScoreV1.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("LfScoreV1OneOf");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into LfScoreV1OneOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(LfScoreV1OneOf1).GetProperty("AdditionalProperties") == null)
                {
                    newLfScoreV1 = new LfScoreV1(JsonConvert.DeserializeObject<LfScoreV1OneOf1>(jsonString, LfScoreV1.SerializerSettings));
                }
                else
                {
                    newLfScoreV1 = new LfScoreV1(JsonConvert.DeserializeObject<LfScoreV1OneOf1>(jsonString, LfScoreV1.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("LfScoreV1OneOf1");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into LfScoreV1OneOf1: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(LfScoreV1OneOf2).GetProperty("AdditionalProperties") == null)
                {
                    newLfScoreV1 = new LfScoreV1(JsonConvert.DeserializeObject<LfScoreV1OneOf2>(jsonString, LfScoreV1.SerializerSettings));
                }
                else
                {
                    newLfScoreV1 = new LfScoreV1(JsonConvert.DeserializeObject<LfScoreV1OneOf2>(jsonString, LfScoreV1.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("LfScoreV1OneOf2");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into LfScoreV1OneOf2: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newLfScoreV1;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for LfScoreV1
    /// </summary>
    public class LfScoreV1JsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(LfScoreV1).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return LfScoreV1.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return LfScoreV1.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
