/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// LfScimUsersListResponse
    /// </summary>
    [DataContract(Name = "ScimUsersListResponse")]
    public partial class LfScimUsersListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LfScimUsersListResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LfScimUsersListResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LfScimUsersListResponse" /> class.
        /// </summary>
        /// <param name="schemas">schemas (required).</param>
        /// <param name="totalResults">totalResults (required).</param>
        /// <param name="startIndex">startIndex (required).</param>
        /// <param name="itemsPerPage">itemsPerPage (required).</param>
        /// <param name="resources">resources (required).</param>
        public LfScimUsersListResponse(List<string> schemas = default, int totalResults = default, int startIndex = default, int itemsPerPage = default, List<LfScimUser> resources = default)
        {
            // to ensure "schemas" is required (not null)
            if (schemas == null)
            {
                throw new ArgumentNullException("schemas is a required property for LfScimUsersListResponse and cannot be null");
            }
            this.Schemas = schemas;
            this.TotalResults = totalResults;
            this.StartIndex = startIndex;
            this.ItemsPerPage = itemsPerPage;
            // to ensure "resources" is required (not null)
            if (resources == null)
            {
                throw new ArgumentNullException("resources is a required property for LfScimUsersListResponse and cannot be null");
            }
            this.Resources = resources;
        }

        /// <summary>
        /// Gets or Sets Schemas
        /// </summary>
        [DataMember(Name = "schemas", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Schemas { get; set; }

        /// <summary>
        /// Gets or Sets TotalResults
        /// </summary>
        [DataMember(Name = "totalResults", IsRequired = true, EmitDefaultValue = true)]
        public int TotalResults { get; set; }

        /// <summary>
        /// Gets or Sets StartIndex
        /// </summary>
        [DataMember(Name = "startIndex", IsRequired = true, EmitDefaultValue = true)]
        public int StartIndex { get; set; }

        /// <summary>
        /// Gets or Sets ItemsPerPage
        /// </summary>
        [DataMember(Name = "itemsPerPage", IsRequired = true, EmitDefaultValue = true)]
        public int ItemsPerPage { get; set; }

        /// <summary>
        /// Gets or Sets Resources
        /// </summary>
        [DataMember(Name = "Resources", IsRequired = true, EmitDefaultValue = true)]
        public List<LfScimUser> Resources { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LfScimUsersListResponse {\n");
            sb.Append("  Schemas: ").Append(Schemas).Append("\n");
            sb.Append("  TotalResults: ").Append(TotalResults).Append("\n");
            sb.Append("  StartIndex: ").Append(StartIndex).Append("\n");
            sb.Append("  ItemsPerPage: ").Append(ItemsPerPage).Append("\n");
            sb.Append("  Resources: ").Append(Resources).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
