/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Langfuse.Client.Client.FileParameter;
using OpenAPIDateConverter = Langfuse.Client.Client.OpenAPIDateConverter;

namespace Langfuse.Client.Model
{
    /// <summary>
    /// LfUtilsMetaResponse
    /// </summary>
    [DataContract(Name = "utilsMetaResponse")]
    public partial class LfUtilsMetaResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LfUtilsMetaResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LfUtilsMetaResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LfUtilsMetaResponse" /> class.
        /// </summary>
        /// <param name="page">current page number (required).</param>
        /// <param name="limit">number of items per page (required).</param>
        /// <param name="totalItems">number of total items given the current filters/selection (if any) (required).</param>
        /// <param name="totalPages">number of total pages given the current limit (required).</param>
        public LfUtilsMetaResponse(int page = default, int limit = default, int totalItems = default, int totalPages = default)
        {
            this.Page = page;
            this.Limit = limit;
            this.TotalItems = totalItems;
            this.TotalPages = totalPages;
        }

        /// <summary>
        /// current page number
        /// </summary>
        /// <value>current page number</value>
        [DataMember(Name = "page", IsRequired = true, EmitDefaultValue = true)]
        public int Page { get; set; }

        /// <summary>
        /// number of items per page
        /// </summary>
        /// <value>number of items per page</value>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public int Limit { get; set; }

        /// <summary>
        /// number of total items given the current filters/selection (if any)
        /// </summary>
        /// <value>number of total items given the current filters/selection (if any)</value>
        [DataMember(Name = "totalItems", IsRequired = true, EmitDefaultValue = true)]
        public int TotalItems { get; set; }

        /// <summary>
        /// number of total pages given the current limit
        /// </summary>
        /// <value>number of total pages given the current limit</value>
        [DataMember(Name = "totalPages", IsRequired = true, EmitDefaultValue = true)]
        public int TotalPages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LfUtilsMetaResponse {\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  TotalItems: ").Append(TotalItems).Append("\n");
            sb.Append("  TotalPages: ").Append(TotalPages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
