/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Langfuse.Client.Client;
using Langfuse.Client.Model;

namespace Langfuse.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICommentsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateCommentRequest"></param>
        /// <returns>LfCreateCommentResponse</returns>
        LfCreateCommentResponse CommentsCreate(LfCreateCommentRequest lfCreateCommentRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateCommentRequest"></param>
        /// <returns>ApiResponse of LfCreateCommentResponse</returns>
        ApiResponse<LfCreateCommentResponse> CommentsCreateWithHttpInfo(LfCreateCommentRequest lfCreateCommentRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all comments
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="objectType">Filter comments by object type (trace, observation, session, prompt). (optional)</param>
        /// <param name="objectId">Filter comments by object id. If objectType is not provided, an error will be thrown. (optional)</param>
        /// <param name="authorUserId">Filter comments by author user id. (optional)</param>
        /// <returns>LfGetCommentsResponse</returns>
        LfGetCommentsResponse CommentsGet(int? page = default, int? limit = default, string? objectType = default, string? objectId = default, string? authorUserId = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all comments
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="objectType">Filter comments by object type (trace, observation, session, prompt). (optional)</param>
        /// <param name="objectId">Filter comments by object id. If objectType is not provided, an error will be thrown. (optional)</param>
        /// <param name="authorUserId">Filter comments by author user id. (optional)</param>
        /// <returns>ApiResponse of LfGetCommentsResponse</returns>
        ApiResponse<LfGetCommentsResponse> CommentsGetWithHttpInfo(int? page = default, int? limit = default, string? objectType = default, string? objectId = default, string? authorUserId = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a comment by id
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="commentId">The unique langfuse identifier of a comment</param>
        /// <returns>LfComment</returns>
        LfComment CommentsGetById(string commentId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a comment by id
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="commentId">The unique langfuse identifier of a comment</param>
        /// <returns>ApiResponse of LfComment</returns>
        ApiResponse<LfComment> CommentsGetByIdWithHttpInfo(string commentId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICommentsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateCommentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfCreateCommentResponse</returns>
        System.Threading.Tasks.Task<LfCreateCommentResponse> CommentsCreateAsync(LfCreateCommentRequest lfCreateCommentRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateCommentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfCreateCommentResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfCreateCommentResponse>> CommentsCreateWithHttpInfoAsync(LfCreateCommentRequest lfCreateCommentRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all comments
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="objectType">Filter comments by object type (trace, observation, session, prompt). (optional)</param>
        /// <param name="objectId">Filter comments by object id. If objectType is not provided, an error will be thrown. (optional)</param>
        /// <param name="authorUserId">Filter comments by author user id. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfGetCommentsResponse</returns>
        System.Threading.Tasks.Task<LfGetCommentsResponse> CommentsGetAsync(int? page = default, int? limit = default, string? objectType = default, string? objectId = default, string? authorUserId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all comments
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="objectType">Filter comments by object type (trace, observation, session, prompt). (optional)</param>
        /// <param name="objectId">Filter comments by object id. If objectType is not provided, an error will be thrown. (optional)</param>
        /// <param name="authorUserId">Filter comments by author user id. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfGetCommentsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfGetCommentsResponse>> CommentsGetWithHttpInfoAsync(int? page = default, int? limit = default, string? objectType = default, string? objectId = default, string? authorUserId = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a comment by id
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="commentId">The unique langfuse identifier of a comment</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfComment</returns>
        System.Threading.Tasks.Task<LfComment> CommentsGetByIdAsync(string commentId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a comment by id
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="commentId">The unique langfuse identifier of a comment</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfComment)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfComment>> CommentsGetByIdWithHttpInfoAsync(string commentId, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICommentsApi : ICommentsApiSync, ICommentsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CommentsApi : IDisposable, ICommentsApi
    {
        private Langfuse.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CommentsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public CommentsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommentsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public CommentsApi(string basePath)
        {
            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                new Langfuse.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommentsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public CommentsApi(Langfuse.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommentsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CommentsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommentsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CommentsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                new Langfuse.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommentsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public CommentsApi(HttpClient client, Langfuse.Client.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommentsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public CommentsApi(Langfuse.Client.Client.ISynchronousClient client, Langfuse.Client.Client.IAsynchronousClient asyncClient, Langfuse.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Langfuse.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Langfuse.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Langfuse.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Langfuse.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Langfuse.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateCommentRequest"></param>
        /// <returns>LfCreateCommentResponse</returns>
        public LfCreateCommentResponse CommentsCreate(LfCreateCommentRequest lfCreateCommentRequest)
        {
            Langfuse.Client.Client.ApiResponse<LfCreateCommentResponse> localVarResponse = CommentsCreateWithHttpInfo(lfCreateCommentRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateCommentRequest"></param>
        /// <returns>ApiResponse of LfCreateCommentResponse</returns>
        public Langfuse.Client.Client.ApiResponse<LfCreateCommentResponse> CommentsCreateWithHttpInfo(LfCreateCommentRequest lfCreateCommentRequest)
        {
            // verify the required parameter 'lfCreateCommentRequest' is set
            if (lfCreateCommentRequest == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'lfCreateCommentRequest' when calling CommentsApi->CommentsCreate");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = lfCreateCommentRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LfCreateCommentResponse>("/api/public/comments", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CommentsCreate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateCommentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfCreateCommentResponse</returns>
        public async System.Threading.Tasks.Task<LfCreateCommentResponse> CommentsCreateAsync(LfCreateCommentRequest lfCreateCommentRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfCreateCommentResponse> localVarResponse = await CommentsCreateWithHttpInfoAsync(lfCreateCommentRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create a comment. Comments may be attached to different object types (trace, observation, session, prompt).
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateCommentRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfCreateCommentResponse)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfCreateCommentResponse>> CommentsCreateWithHttpInfoAsync(LfCreateCommentRequest lfCreateCommentRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'lfCreateCommentRequest' is set
            if (lfCreateCommentRequest == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'lfCreateCommentRequest' when calling CommentsApi->CommentsCreate");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = lfCreateCommentRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<LfCreateCommentResponse>("/api/public/comments", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CommentsCreate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get all comments
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="objectType">Filter comments by object type (trace, observation, session, prompt). (optional)</param>
        /// <param name="objectId">Filter comments by object id. If objectType is not provided, an error will be thrown. (optional)</param>
        /// <param name="authorUserId">Filter comments by author user id. (optional)</param>
        /// <returns>LfGetCommentsResponse</returns>
        public LfGetCommentsResponse CommentsGet(int? page = default, int? limit = default, string? objectType = default, string? objectId = default, string? authorUserId = default)
        {
            Langfuse.Client.Client.ApiResponse<LfGetCommentsResponse> localVarResponse = CommentsGetWithHttpInfo(page, limit, objectType, objectId, authorUserId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all comments
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="objectType">Filter comments by object type (trace, observation, session, prompt). (optional)</param>
        /// <param name="objectId">Filter comments by object id. If objectType is not provided, an error will be thrown. (optional)</param>
        /// <param name="authorUserId">Filter comments by author user id. (optional)</param>
        /// <returns>ApiResponse of LfGetCommentsResponse</returns>
        public Langfuse.Client.Client.ApiResponse<LfGetCommentsResponse> CommentsGetWithHttpInfo(int? page = default, int? limit = default, string? objectType = default, string? objectId = default, string? authorUserId = default)
        {
            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (objectType != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "objectType", objectType));
            }
            if (objectId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "objectId", objectId));
            }
            if (authorUserId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "authorUserId", authorUserId));
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfGetCommentsResponse>("/api/public/comments", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CommentsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get all comments
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="objectType">Filter comments by object type (trace, observation, session, prompt). (optional)</param>
        /// <param name="objectId">Filter comments by object id. If objectType is not provided, an error will be thrown. (optional)</param>
        /// <param name="authorUserId">Filter comments by author user id. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfGetCommentsResponse</returns>
        public async System.Threading.Tasks.Task<LfGetCommentsResponse> CommentsGetAsync(int? page = default, int? limit = default, string? objectType = default, string? objectId = default, string? authorUserId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfGetCommentsResponse> localVarResponse = await CommentsGetWithHttpInfoAsync(page, limit, objectType, objectId, authorUserId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all comments
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="objectType">Filter comments by object type (trace, observation, session, prompt). (optional)</param>
        /// <param name="objectId">Filter comments by object id. If objectType is not provided, an error will be thrown. (optional)</param>
        /// <param name="authorUserId">Filter comments by author user id. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfGetCommentsResponse)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfGetCommentsResponse>> CommentsGetWithHttpInfoAsync(int? page = default, int? limit = default, string? objectType = default, string? objectId = default, string? authorUserId = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (objectType != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "objectType", objectType));
            }
            if (objectId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "objectId", objectId));
            }
            if (authorUserId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "authorUserId", authorUserId));
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfGetCommentsResponse>("/api/public/comments", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CommentsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get a comment by id
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="commentId">The unique langfuse identifier of a comment</param>
        /// <returns>LfComment</returns>
        public LfComment CommentsGetById(string commentId)
        {
            Langfuse.Client.Client.ApiResponse<LfComment> localVarResponse = CommentsGetByIdWithHttpInfo(commentId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get a comment by id
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="commentId">The unique langfuse identifier of a comment</param>
        /// <returns>ApiResponse of LfComment</returns>
        public Langfuse.Client.Client.ApiResponse<LfComment> CommentsGetByIdWithHttpInfo(string commentId)
        {
            // verify the required parameter 'commentId' is set
            if (commentId == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'commentId' when calling CommentsApi->CommentsGetById");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("commentId", Langfuse.Client.Client.ClientUtils.ParameterToString(commentId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfComment>("/api/public/comments/{commentId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CommentsGetById", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get a comment by id
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="commentId">The unique langfuse identifier of a comment</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfComment</returns>
        public async System.Threading.Tasks.Task<LfComment> CommentsGetByIdAsync(string commentId, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfComment> localVarResponse = await CommentsGetByIdWithHttpInfoAsync(commentId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get a comment by id
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="commentId">The unique langfuse identifier of a comment</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfComment)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfComment>> CommentsGetByIdWithHttpInfoAsync(string commentId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'commentId' is set
            if (commentId == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'commentId' when calling CommentsApi->CommentsGetById");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("commentId", Langfuse.Client.Client.ClientUtils.ParameterToString(commentId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfComment>("/api/public/comments/{commentId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CommentsGetById", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
