/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Langfuse.Client.Client;
using Langfuse.Client.Model;

namespace Langfuse.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDatasetRunItemsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a dataset run item
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateDatasetRunItemRequest"></param>
        /// <returns>LfDatasetRunItem</returns>
        LfDatasetRunItem DatasetRunItemsCreate(LfCreateDatasetRunItemRequest lfCreateDatasetRunItemRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a dataset run item
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateDatasetRunItemRequest"></param>
        /// <returns>ApiResponse of LfDatasetRunItem</returns>
        ApiResponse<LfDatasetRunItem> DatasetRunItemsCreateWithHttpInfo(LfCreateDatasetRunItemRequest lfCreateDatasetRunItemRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List dataset run items
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="datasetId"></param>
        /// <param name="runName"></param>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <returns>LfPaginatedDatasetRunItems</returns>
        LfPaginatedDatasetRunItems DatasetRunItemsList(string datasetId, string runName, int? page = default, int? limit = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List dataset run items
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="datasetId"></param>
        /// <param name="runName"></param>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <returns>ApiResponse of LfPaginatedDatasetRunItems</returns>
        ApiResponse<LfPaginatedDatasetRunItems> DatasetRunItemsListWithHttpInfo(string datasetId, string runName, int? page = default, int? limit = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDatasetRunItemsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a dataset run item
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateDatasetRunItemRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfDatasetRunItem</returns>
        System.Threading.Tasks.Task<LfDatasetRunItem> DatasetRunItemsCreateAsync(LfCreateDatasetRunItemRequest lfCreateDatasetRunItemRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a dataset run item
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateDatasetRunItemRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfDatasetRunItem)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfDatasetRunItem>> DatasetRunItemsCreateWithHttpInfoAsync(LfCreateDatasetRunItemRequest lfCreateDatasetRunItemRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List dataset run items
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="datasetId"></param>
        /// <param name="runName"></param>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfPaginatedDatasetRunItems</returns>
        System.Threading.Tasks.Task<LfPaginatedDatasetRunItems> DatasetRunItemsListAsync(string datasetId, string runName, int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List dataset run items
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="datasetId"></param>
        /// <param name="runName"></param>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfPaginatedDatasetRunItems)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfPaginatedDatasetRunItems>> DatasetRunItemsListWithHttpInfoAsync(string datasetId, string runName, int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDatasetRunItemsApi : IDatasetRunItemsApiSync, IDatasetRunItemsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DatasetRunItemsApi : IDisposable, IDatasetRunItemsApi
    {
        private Langfuse.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetRunItemsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public DatasetRunItemsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetRunItemsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public DatasetRunItemsApi(string basePath)
        {
            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                new Langfuse.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetRunItemsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public DatasetRunItemsApi(Langfuse.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetRunItemsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DatasetRunItemsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetRunItemsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DatasetRunItemsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                new Langfuse.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetRunItemsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DatasetRunItemsApi(HttpClient client, Langfuse.Client.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DatasetRunItemsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DatasetRunItemsApi(Langfuse.Client.Client.ISynchronousClient client, Langfuse.Client.Client.IAsynchronousClient asyncClient, Langfuse.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Langfuse.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Langfuse.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Langfuse.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Langfuse.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Langfuse.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Create a dataset run item
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateDatasetRunItemRequest"></param>
        /// <returns>LfDatasetRunItem</returns>
        public LfDatasetRunItem DatasetRunItemsCreate(LfCreateDatasetRunItemRequest lfCreateDatasetRunItemRequest)
        {
            Langfuse.Client.Client.ApiResponse<LfDatasetRunItem> localVarResponse = DatasetRunItemsCreateWithHttpInfo(lfCreateDatasetRunItemRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create a dataset run item
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateDatasetRunItemRequest"></param>
        /// <returns>ApiResponse of LfDatasetRunItem</returns>
        public Langfuse.Client.Client.ApiResponse<LfDatasetRunItem> DatasetRunItemsCreateWithHttpInfo(LfCreateDatasetRunItemRequest lfCreateDatasetRunItemRequest)
        {
            // verify the required parameter 'lfCreateDatasetRunItemRequest' is set
            if (lfCreateDatasetRunItemRequest == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'lfCreateDatasetRunItemRequest' when calling DatasetRunItemsApi->DatasetRunItemsCreate");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = lfCreateDatasetRunItemRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LfDatasetRunItem>("/api/public/dataset-run-items", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DatasetRunItemsCreate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Create a dataset run item
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateDatasetRunItemRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfDatasetRunItem</returns>
        public async System.Threading.Tasks.Task<LfDatasetRunItem> DatasetRunItemsCreateAsync(LfCreateDatasetRunItemRequest lfCreateDatasetRunItemRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfDatasetRunItem> localVarResponse = await DatasetRunItemsCreateWithHttpInfoAsync(lfCreateDatasetRunItemRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create a dataset run item
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateDatasetRunItemRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfDatasetRunItem)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfDatasetRunItem>> DatasetRunItemsCreateWithHttpInfoAsync(LfCreateDatasetRunItemRequest lfCreateDatasetRunItemRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'lfCreateDatasetRunItemRequest' is set
            if (lfCreateDatasetRunItemRequest == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'lfCreateDatasetRunItemRequest' when calling DatasetRunItemsApi->DatasetRunItemsCreate");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = lfCreateDatasetRunItemRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<LfDatasetRunItem>("/api/public/dataset-run-items", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DatasetRunItemsCreate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  List dataset run items
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="datasetId"></param>
        /// <param name="runName"></param>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <returns>LfPaginatedDatasetRunItems</returns>
        public LfPaginatedDatasetRunItems DatasetRunItemsList(string datasetId, string runName, int? page = default, int? limit = default)
        {
            Langfuse.Client.Client.ApiResponse<LfPaginatedDatasetRunItems> localVarResponse = DatasetRunItemsListWithHttpInfo(datasetId, runName, page, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  List dataset run items
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="datasetId"></param>
        /// <param name="runName"></param>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <returns>ApiResponse of LfPaginatedDatasetRunItems</returns>
        public Langfuse.Client.Client.ApiResponse<LfPaginatedDatasetRunItems> DatasetRunItemsListWithHttpInfo(string datasetId, string runName, int? page = default, int? limit = default)
        {
            // verify the required parameter 'datasetId' is set
            if (datasetId == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'datasetId' when calling DatasetRunItemsApi->DatasetRunItemsList");

            // verify the required parameter 'runName' is set
            if (runName == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'runName' when calling DatasetRunItemsApi->DatasetRunItemsList");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "datasetId", datasetId));
            localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "runName", runName));
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfPaginatedDatasetRunItems>("/api/public/dataset-run-items", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DatasetRunItemsList", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  List dataset run items
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="datasetId"></param>
        /// <param name="runName"></param>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfPaginatedDatasetRunItems</returns>
        public async System.Threading.Tasks.Task<LfPaginatedDatasetRunItems> DatasetRunItemsListAsync(string datasetId, string runName, int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfPaginatedDatasetRunItems> localVarResponse = await DatasetRunItemsListWithHttpInfoAsync(datasetId, runName, page, limit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  List dataset run items
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="datasetId"></param>
        /// <param name="runName"></param>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfPaginatedDatasetRunItems)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfPaginatedDatasetRunItems>> DatasetRunItemsListWithHttpInfoAsync(string datasetId, string runName, int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'datasetId' is set
            if (datasetId == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'datasetId' when calling DatasetRunItemsApi->DatasetRunItemsList");

            // verify the required parameter 'runName' is set
            if (runName == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'runName' when calling DatasetRunItemsApi->DatasetRunItemsList");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "datasetId", datasetId));
            localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "runName", runName));
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfPaginatedDatasetRunItems>("/api/public/dataset-run-items", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DatasetRunItemsList", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
