/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Langfuse.Client.Client;
using Langfuse.Client.Model;

namespace Langfuse.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IModelsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a model
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateModelRequest"></param>
        /// <returns>LfModel</returns>
        LfModel ModelsCreate(LfCreateModelRequest lfCreateModelRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a model
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateModelRequest"></param>
        /// <returns>ApiResponse of LfModel</returns>
        ApiResponse<LfModel> ModelsCreateWithHttpInfo(LfCreateModelRequest lfCreateModelRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Delete a model. Cannot delete models managed by Langfuse. You can create your own definition with the same modelName to override the definition though.
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns></returns>
        void ModelsDelete(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Delete a model. Cannot delete models managed by Langfuse. You can create your own definition with the same modelName to override the definition though.
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ModelsDeleteWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a model
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>LfModel</returns>
        LfModel ModelsGet(string id);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a model
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of LfModel</returns>
        ApiResponse<LfModel> ModelsGetWithHttpInfo(string id);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all models
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <returns>LfPaginatedModels</returns>
        LfPaginatedModels ModelsList(int? page = default, int? limit = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all models
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <returns>ApiResponse of LfPaginatedModels</returns>
        ApiResponse<LfPaginatedModels> ModelsListWithHttpInfo(int? page = default, int? limit = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IModelsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a model
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateModelRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfModel</returns>
        System.Threading.Tasks.Task<LfModel> ModelsCreateAsync(LfCreateModelRequest lfCreateModelRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a model
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateModelRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfModel>> ModelsCreateWithHttpInfoAsync(LfCreateModelRequest lfCreateModelRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Delete a model. Cannot delete models managed by Langfuse. You can create your own definition with the same modelName to override the definition though.
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ModelsDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Delete a model. Cannot delete models managed by Langfuse. You can create your own definition with the same modelName to override the definition though.
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ModelsDeleteWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a model
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfModel</returns>
        System.Threading.Tasks.Task<LfModel> ModelsGetAsync(string id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a model
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfModel>> ModelsGetWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all models
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfPaginatedModels</returns>
        System.Threading.Tasks.Task<LfPaginatedModels> ModelsListAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all models
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfPaginatedModels)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfPaginatedModels>> ModelsListWithHttpInfoAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IModelsApi : IModelsApiSync, IModelsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ModelsApi : IDisposable, IModelsApi
    {
        private Langfuse.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ModelsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ModelsApi(string basePath)
        {
            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                new Langfuse.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ModelsApi(Langfuse.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ModelsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ModelsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                new Langfuse.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ModelsApi(HttpClient client, Langfuse.Client.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ModelsApi(Langfuse.Client.Client.ISynchronousClient client, Langfuse.Client.Client.IAsynchronousClient asyncClient, Langfuse.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Langfuse.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Langfuse.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Langfuse.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Langfuse.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Langfuse.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Create a model
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateModelRequest"></param>
        /// <returns>LfModel</returns>
        public LfModel ModelsCreate(LfCreateModelRequest lfCreateModelRequest)
        {
            Langfuse.Client.Client.ApiResponse<LfModel> localVarResponse = ModelsCreateWithHttpInfo(lfCreateModelRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create a model
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateModelRequest"></param>
        /// <returns>ApiResponse of LfModel</returns>
        public Langfuse.Client.Client.ApiResponse<LfModel> ModelsCreateWithHttpInfo(LfCreateModelRequest lfCreateModelRequest)
        {
            // verify the required parameter 'lfCreateModelRequest' is set
            if (lfCreateModelRequest == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'lfCreateModelRequest' when calling ModelsApi->ModelsCreate");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = lfCreateModelRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LfModel>("/api/public/models", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ModelsCreate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Create a model
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateModelRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfModel</returns>
        public async System.Threading.Tasks.Task<LfModel> ModelsCreateAsync(LfCreateModelRequest lfCreateModelRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfModel> localVarResponse = await ModelsCreateWithHttpInfoAsync(lfCreateModelRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create a model
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateModelRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfModel)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfModel>> ModelsCreateWithHttpInfoAsync(LfCreateModelRequest lfCreateModelRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'lfCreateModelRequest' is set
            if (lfCreateModelRequest == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'lfCreateModelRequest' when calling ModelsApi->ModelsCreate");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = lfCreateModelRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<LfModel>("/api/public/models", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ModelsCreate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Delete a model. Cannot delete models managed by Langfuse. You can create your own definition with the same modelName to override the definition though.
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns></returns>
        public void ModelsDelete(string id)
        {
            ModelsDeleteWithHttpInfo(id);
        }

        /// <summary>
        ///  Delete a model. Cannot delete models managed by Langfuse. You can create your own definition with the same modelName to override the definition though.
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Langfuse.Client.Client.ApiResponse<Object> ModelsDeleteWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ModelsApi->ModelsDelete");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Langfuse.Client.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/public/models/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ModelsDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Delete a model. Cannot delete models managed by Langfuse. You can create your own definition with the same modelName to override the definition though.
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ModelsDeleteAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            await ModelsDeleteWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  Delete a model. Cannot delete models managed by Langfuse. You can create your own definition with the same modelName to override the definition though.
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<Object>> ModelsDeleteWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ModelsApi->ModelsDelete");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Langfuse.Client.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api/public/models/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ModelsDelete", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get a model
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>LfModel</returns>
        public LfModel ModelsGet(string id)
        {
            Langfuse.Client.Client.ApiResponse<LfModel> localVarResponse = ModelsGetWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get a model
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of LfModel</returns>
        public Langfuse.Client.Client.ApiResponse<LfModel> ModelsGetWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ModelsApi->ModelsGet");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Langfuse.Client.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfModel>("/api/public/models/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ModelsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get a model
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfModel</returns>
        public async System.Threading.Tasks.Task<LfModel> ModelsGetAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfModel> localVarResponse = await ModelsGetWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get a model
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfModel)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfModel>> ModelsGetWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ModelsApi->ModelsGet");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Langfuse.Client.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfModel>("/api/public/models/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ModelsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get all models
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <returns>LfPaginatedModels</returns>
        public LfPaginatedModels ModelsList(int? page = default, int? limit = default)
        {
            Langfuse.Client.Client.ApiResponse<LfPaginatedModels> localVarResponse = ModelsListWithHttpInfo(page, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all models
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <returns>ApiResponse of LfPaginatedModels</returns>
        public Langfuse.Client.Client.ApiResponse<LfPaginatedModels> ModelsListWithHttpInfo(int? page = default, int? limit = default)
        {
            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfPaginatedModels>("/api/public/models", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ModelsList", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get all models
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfPaginatedModels</returns>
        public async System.Threading.Tasks.Task<LfPaginatedModels> ModelsListAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfPaginatedModels> localVarResponse = await ModelsListWithHttpInfoAsync(page, limit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all models
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">page number, starts at 1 (optional)</param>
        /// <param name="limit">limit of items per page (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfPaginatedModels)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfPaginatedModels>> ModelsListWithHttpInfoAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfPaginatedModels>("/api/public/models", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ModelsList", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
