/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Langfuse.Client.Client;
using Langfuse.Client.Model;

namespace Langfuse.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IScimApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a new user in the organization (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfScimCreateUserRequest"></param>
        /// <returns>LfScimUser</returns>
        LfScimUser ScimCreateUser(LfScimCreateUserRequest lfScimCreateUserRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a new user in the organization (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfScimCreateUserRequest"></param>
        /// <returns>ApiResponse of LfScimUser</returns>
        ApiResponse<LfScimUser> ScimCreateUserWithHttpInfo(LfScimCreateUserRequest lfScimCreateUserRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Remove a user from the organization (requires organization-scoped API key). Note that this only removes the user from the organization but does not delete the user entity itself.
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>Object</returns>
        Object ScimDeleteUser(string userId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Remove a user from the organization (requires organization-scoped API key). Note that this only removes the user from the organization but does not delete the user entity itself.
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ScimDeleteUserWithHttpInfo(string userId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Resource Types (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LfResourceTypesResponse</returns>
        LfResourceTypesResponse ScimGetResourceTypes();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Resource Types (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LfResourceTypesResponse</returns>
        ApiResponse<LfResourceTypesResponse> ScimGetResourceTypesWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Schemas (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LfSchemasResponse</returns>
        LfSchemasResponse ScimGetSchemas();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Schemas (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LfSchemasResponse</returns>
        ApiResponse<LfSchemasResponse> ScimGetSchemasWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Service Provider Configuration (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LfServiceProviderConfig</returns>
        LfServiceProviderConfig ScimGetServiceProviderConfig();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Service Provider Configuration (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LfServiceProviderConfig</returns>
        ApiResponse<LfServiceProviderConfig> ScimGetServiceProviderConfigWithHttpInfo();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a specific user by ID (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>LfScimUser</returns>
        LfScimUser ScimGetUser(string userId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a specific user by ID (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>ApiResponse of LfScimUser</returns>
        ApiResponse<LfScimUser> ScimGetUserWithHttpInfo(string userId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List users in the organization (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter expression (e.g. userName eq \&quot;value\&quot;) (optional)</param>
        /// <param name="startIndex">1-based index of the first result to return (default 1) (optional)</param>
        /// <param name="count">Maximum number of results to return (default 100) (optional)</param>
        /// <returns>LfScimUsersListResponse</returns>
        LfScimUsersListResponse ScimListUsers(string? filter = default, int? startIndex = default, int? count = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List users in the organization (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter expression (e.g. userName eq \&quot;value\&quot;) (optional)</param>
        /// <param name="startIndex">1-based index of the first result to return (default 1) (optional)</param>
        /// <param name="count">Maximum number of results to return (default 100) (optional)</param>
        /// <returns>ApiResponse of LfScimUsersListResponse</returns>
        ApiResponse<LfScimUsersListResponse> ScimListUsersWithHttpInfo(string? filter = default, int? startIndex = default, int? count = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IScimApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a new user in the organization (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfScimCreateUserRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScimUser</returns>
        System.Threading.Tasks.Task<LfScimUser> ScimCreateUserAsync(LfScimCreateUserRequest lfScimCreateUserRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a new user in the organization (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfScimCreateUserRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScimUser)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfScimUser>> ScimCreateUserWithHttpInfoAsync(LfScimCreateUserRequest lfScimCreateUserRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Remove a user from the organization (requires organization-scoped API key). Note that this only removes the user from the organization but does not delete the user entity itself.
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ScimDeleteUserAsync(string userId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Remove a user from the organization (requires organization-scoped API key). Note that this only removes the user from the organization but does not delete the user entity itself.
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ScimDeleteUserWithHttpInfoAsync(string userId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Resource Types (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfResourceTypesResponse</returns>
        System.Threading.Tasks.Task<LfResourceTypesResponse> ScimGetResourceTypesAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Resource Types (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfResourceTypesResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfResourceTypesResponse>> ScimGetResourceTypesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Schemas (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfSchemasResponse</returns>
        System.Threading.Tasks.Task<LfSchemasResponse> ScimGetSchemasAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Schemas (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfSchemasResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfSchemasResponse>> ScimGetSchemasWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Service Provider Configuration (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfServiceProviderConfig</returns>
        System.Threading.Tasks.Task<LfServiceProviderConfig> ScimGetServiceProviderConfigAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get SCIM Service Provider Configuration (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfServiceProviderConfig)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfServiceProviderConfig>> ScimGetServiceProviderConfigWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a specific user by ID (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScimUser</returns>
        System.Threading.Tasks.Task<LfScimUser> ScimGetUserAsync(string userId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a specific user by ID (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScimUser)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfScimUser>> ScimGetUserWithHttpInfoAsync(string userId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List users in the organization (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter expression (e.g. userName eq \&quot;value\&quot;) (optional)</param>
        /// <param name="startIndex">1-based index of the first result to return (default 1) (optional)</param>
        /// <param name="count">Maximum number of results to return (default 100) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScimUsersListResponse</returns>
        System.Threading.Tasks.Task<LfScimUsersListResponse> ScimListUsersAsync(string? filter = default, int? startIndex = default, int? count = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// List users in the organization (requires organization-scoped API key)
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter expression (e.g. userName eq \&quot;value\&quot;) (optional)</param>
        /// <param name="startIndex">1-based index of the first result to return (default 1) (optional)</param>
        /// <param name="count">Maximum number of results to return (default 100) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScimUsersListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfScimUsersListResponse>> ScimListUsersWithHttpInfoAsync(string? filter = default, int? startIndex = default, int? count = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IScimApi : IScimApiSync, IScimApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ScimApi : IDisposable, IScimApi
    {
        private Langfuse.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ScimApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ScimApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScimApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ScimApi(string basePath)
        {
            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                new Langfuse.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScimApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ScimApi(Langfuse.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScimApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ScimApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScimApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ScimApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                new Langfuse.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScimApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ScimApi(HttpClient client, Langfuse.Client.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScimApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ScimApi(Langfuse.Client.Client.ISynchronousClient client, Langfuse.Client.Client.IAsynchronousClient asyncClient, Langfuse.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Langfuse.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Langfuse.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Langfuse.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Langfuse.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Langfuse.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Create a new user in the organization (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfScimCreateUserRequest"></param>
        /// <returns>LfScimUser</returns>
        public LfScimUser ScimCreateUser(LfScimCreateUserRequest lfScimCreateUserRequest)
        {
            Langfuse.Client.Client.ApiResponse<LfScimUser> localVarResponse = ScimCreateUserWithHttpInfo(lfScimCreateUserRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create a new user in the organization (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfScimCreateUserRequest"></param>
        /// <returns>ApiResponse of LfScimUser</returns>
        public Langfuse.Client.Client.ApiResponse<LfScimUser> ScimCreateUserWithHttpInfo(LfScimCreateUserRequest lfScimCreateUserRequest)
        {
            // verify the required parameter 'lfScimCreateUserRequest' is set
            if (lfScimCreateUserRequest == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'lfScimCreateUserRequest' when calling ScimApi->ScimCreateUser");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = lfScimCreateUserRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LfScimUser>("/api/public/scim/Users", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimCreateUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Create a new user in the organization (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfScimCreateUserRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScimUser</returns>
        public async System.Threading.Tasks.Task<LfScimUser> ScimCreateUserAsync(LfScimCreateUserRequest lfScimCreateUserRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfScimUser> localVarResponse = await ScimCreateUserWithHttpInfoAsync(lfScimCreateUserRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create a new user in the organization (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfScimCreateUserRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScimUser)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfScimUser>> ScimCreateUserWithHttpInfoAsync(LfScimCreateUserRequest lfScimCreateUserRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'lfScimCreateUserRequest' is set
            if (lfScimCreateUserRequest == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'lfScimCreateUserRequest' when calling ScimApi->ScimCreateUser");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = lfScimCreateUserRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<LfScimUser>("/api/public/scim/Users", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimCreateUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Remove a user from the organization (requires organization-scoped API key). Note that this only removes the user from the organization but does not delete the user entity itself.
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>Object</returns>
        public Object ScimDeleteUser(string userId)
        {
            Langfuse.Client.Client.ApiResponse<Object> localVarResponse = ScimDeleteUserWithHttpInfo(userId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Remove a user from the organization (requires organization-scoped API key). Note that this only removes the user from the organization but does not delete the user entity itself.
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>ApiResponse of Object</returns>
        public Langfuse.Client.Client.ApiResponse<Object> ScimDeleteUserWithHttpInfo(string userId)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'userId' when calling ScimApi->ScimDeleteUser");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("userId", Langfuse.Client.Client.ClientUtils.ParameterToString(userId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/public/scim/Users/{userId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimDeleteUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Remove a user from the organization (requires organization-scoped API key). Note that this only removes the user from the organization but does not delete the user entity itself.
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ScimDeleteUserAsync(string userId, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<Object> localVarResponse = await ScimDeleteUserWithHttpInfoAsync(userId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Remove a user from the organization (requires organization-scoped API key). Note that this only removes the user from the organization but does not delete the user entity itself.
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<Object>> ScimDeleteUserWithHttpInfoAsync(string userId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'userId' when calling ScimApi->ScimDeleteUser");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("userId", Langfuse.Client.Client.ClientUtils.ParameterToString(userId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api/public/scim/Users/{userId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimDeleteUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get SCIM Resource Types (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LfResourceTypesResponse</returns>
        public LfResourceTypesResponse ScimGetResourceTypes()
        {
            Langfuse.Client.Client.ApiResponse<LfResourceTypesResponse> localVarResponse = ScimGetResourceTypesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get SCIM Resource Types (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LfResourceTypesResponse</returns>
        public Langfuse.Client.Client.ApiResponse<LfResourceTypesResponse> ScimGetResourceTypesWithHttpInfo()
        {
            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfResourceTypesResponse>("/api/public/scim/ResourceTypes", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimGetResourceTypes", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get SCIM Resource Types (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfResourceTypesResponse</returns>
        public async System.Threading.Tasks.Task<LfResourceTypesResponse> ScimGetResourceTypesAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfResourceTypesResponse> localVarResponse = await ScimGetResourceTypesWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get SCIM Resource Types (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfResourceTypesResponse)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfResourceTypesResponse>> ScimGetResourceTypesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfResourceTypesResponse>("/api/public/scim/ResourceTypes", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimGetResourceTypes", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get SCIM Schemas (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LfSchemasResponse</returns>
        public LfSchemasResponse ScimGetSchemas()
        {
            Langfuse.Client.Client.ApiResponse<LfSchemasResponse> localVarResponse = ScimGetSchemasWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get SCIM Schemas (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LfSchemasResponse</returns>
        public Langfuse.Client.Client.ApiResponse<LfSchemasResponse> ScimGetSchemasWithHttpInfo()
        {
            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfSchemasResponse>("/api/public/scim/Schemas", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimGetSchemas", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get SCIM Schemas (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfSchemasResponse</returns>
        public async System.Threading.Tasks.Task<LfSchemasResponse> ScimGetSchemasAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfSchemasResponse> localVarResponse = await ScimGetSchemasWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get SCIM Schemas (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfSchemasResponse)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfSchemasResponse>> ScimGetSchemasWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfSchemasResponse>("/api/public/scim/Schemas", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimGetSchemas", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get SCIM Service Provider Configuration (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>LfServiceProviderConfig</returns>
        public LfServiceProviderConfig ScimGetServiceProviderConfig()
        {
            Langfuse.Client.Client.ApiResponse<LfServiceProviderConfig> localVarResponse = ScimGetServiceProviderConfigWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get SCIM Service Provider Configuration (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of LfServiceProviderConfig</returns>
        public Langfuse.Client.Client.ApiResponse<LfServiceProviderConfig> ScimGetServiceProviderConfigWithHttpInfo()
        {
            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfServiceProviderConfig>("/api/public/scim/ServiceProviderConfig", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimGetServiceProviderConfig", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get SCIM Service Provider Configuration (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfServiceProviderConfig</returns>
        public async System.Threading.Tasks.Task<LfServiceProviderConfig> ScimGetServiceProviderConfigAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfServiceProviderConfig> localVarResponse = await ScimGetServiceProviderConfigWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get SCIM Service Provider Configuration (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfServiceProviderConfig)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfServiceProviderConfig>> ScimGetServiceProviderConfigWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfServiceProviderConfig>("/api/public/scim/ServiceProviderConfig", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimGetServiceProviderConfig", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get a specific user by ID (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>LfScimUser</returns>
        public LfScimUser ScimGetUser(string userId)
        {
            Langfuse.Client.Client.ApiResponse<LfScimUser> localVarResponse = ScimGetUserWithHttpInfo(userId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get a specific user by ID (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <returns>ApiResponse of LfScimUser</returns>
        public Langfuse.Client.Client.ApiResponse<LfScimUser> ScimGetUserWithHttpInfo(string userId)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'userId' when calling ScimApi->ScimGetUser");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("userId", Langfuse.Client.Client.ClientUtils.ParameterToString(userId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfScimUser>("/api/public/scim/Users/{userId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimGetUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get a specific user by ID (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScimUser</returns>
        public async System.Threading.Tasks.Task<LfScimUser> ScimGetUserAsync(string userId, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfScimUser> localVarResponse = await ScimGetUserWithHttpInfoAsync(userId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get a specific user by ID (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScimUser)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfScimUser>> ScimGetUserWithHttpInfoAsync(string userId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'userId' when calling ScimApi->ScimGetUser");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("userId", Langfuse.Client.Client.ClientUtils.ParameterToString(userId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfScimUser>("/api/public/scim/Users/{userId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimGetUser", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  List users in the organization (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter expression (e.g. userName eq \&quot;value\&quot;) (optional)</param>
        /// <param name="startIndex">1-based index of the first result to return (default 1) (optional)</param>
        /// <param name="count">Maximum number of results to return (default 100) (optional)</param>
        /// <returns>LfScimUsersListResponse</returns>
        public LfScimUsersListResponse ScimListUsers(string? filter = default, int? startIndex = default, int? count = default)
        {
            Langfuse.Client.Client.ApiResponse<LfScimUsersListResponse> localVarResponse = ScimListUsersWithHttpInfo(filter, startIndex, count);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  List users in the organization (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter expression (e.g. userName eq \&quot;value\&quot;) (optional)</param>
        /// <param name="startIndex">1-based index of the first result to return (default 1) (optional)</param>
        /// <param name="count">Maximum number of results to return (default 100) (optional)</param>
        /// <returns>ApiResponse of LfScimUsersListResponse</returns>
        public Langfuse.Client.Client.ApiResponse<LfScimUsersListResponse> ScimListUsersWithHttpInfo(string? filter = default, int? startIndex = default, int? count = default)
        {
            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (startIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "startIndex", startIndex));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfScimUsersListResponse>("/api/public/scim/Users", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimListUsers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  List users in the organization (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter expression (e.g. userName eq \&quot;value\&quot;) (optional)</param>
        /// <param name="startIndex">1-based index of the first result to return (default 1) (optional)</param>
        /// <param name="count">Maximum number of results to return (default 100) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScimUsersListResponse</returns>
        public async System.Threading.Tasks.Task<LfScimUsersListResponse> ScimListUsersAsync(string? filter = default, int? startIndex = default, int? count = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfScimUsersListResponse> localVarResponse = await ScimListUsersWithHttpInfoAsync(filter, startIndex, count, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  List users in the organization (requires organization-scoped API key)
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter">Filter expression (e.g. userName eq \&quot;value\&quot;) (optional)</param>
        /// <param name="startIndex">1-based index of the first result to return (default 1) (optional)</param>
        /// <param name="count">Maximum number of results to return (default 100) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScimUsersListResponse)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfScimUsersListResponse>> ScimListUsersWithHttpInfoAsync(string? filter = default, int? startIndex = default, int? count = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (startIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "startIndex", startIndex));
            }
            if (count != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "count", count));
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfScimUsersListResponse>("/api/public/scim/Users", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScimListUsers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
