/*
 * langfuse
 *
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Langfuse.Client.Client;
using Langfuse.Client.Model;

namespace Langfuse.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IScoreConfigsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a score configuration (config). Score configs are used to define the structure of scores
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateScoreConfigRequest"></param>
        /// <returns>LfScoreConfig</returns>
        LfScoreConfig ScoreConfigsCreate(LfCreateScoreConfigRequest lfCreateScoreConfigRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a score configuration (config). Score configs are used to define the structure of scores
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateScoreConfigRequest"></param>
        /// <returns>ApiResponse of LfScoreConfig</returns>
        ApiResponse<LfScoreConfig> ScoreConfigsCreateWithHttpInfo(LfCreateScoreConfigRequest lfCreateScoreConfigRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all score configs
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <returns>LfScoreConfigs</returns>
        LfScoreConfigs ScoreConfigsGet(int? page = default, int? limit = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all score configs
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <returns>ApiResponse of LfScoreConfigs</returns>
        ApiResponse<LfScoreConfigs> ScoreConfigsGetWithHttpInfo(int? page = default, int? limit = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a score config
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configId">The unique langfuse identifier of a score config</param>
        /// <returns>LfScoreConfig</returns>
        LfScoreConfig ScoreConfigsGetById(string configId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a score config
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configId">The unique langfuse identifier of a score config</param>
        /// <returns>ApiResponse of LfScoreConfig</returns>
        ApiResponse<LfScoreConfig> ScoreConfigsGetByIdWithHttpInfo(string configId);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IScoreConfigsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a score configuration (config). Score configs are used to define the structure of scores
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateScoreConfigRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScoreConfig</returns>
        System.Threading.Tasks.Task<LfScoreConfig> ScoreConfigsCreateAsync(LfCreateScoreConfigRequest lfCreateScoreConfigRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Create a score configuration (config). Score configs are used to define the structure of scores
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateScoreConfigRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScoreConfig)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfScoreConfig>> ScoreConfigsCreateWithHttpInfoAsync(LfCreateScoreConfigRequest lfCreateScoreConfigRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all score configs
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScoreConfigs</returns>
        System.Threading.Tasks.Task<LfScoreConfigs> ScoreConfigsGetAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all score configs
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScoreConfigs)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfScoreConfigs>> ScoreConfigsGetWithHttpInfoAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a score config
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configId">The unique langfuse identifier of a score config</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScoreConfig</returns>
        System.Threading.Tasks.Task<LfScoreConfig> ScoreConfigsGetByIdAsync(string configId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get a score config
        /// </remarks>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configId">The unique langfuse identifier of a score config</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScoreConfig)</returns>
        System.Threading.Tasks.Task<ApiResponse<LfScoreConfig>> ScoreConfigsGetByIdWithHttpInfoAsync(string configId, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IScoreConfigsApi : IScoreConfigsApiSync, IScoreConfigsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ScoreConfigsApi : IDisposable, IScoreConfigsApi
    {
        private Langfuse.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ScoreConfigsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ScoreConfigsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScoreConfigsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ScoreConfigsApi(string basePath)
        {
            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                new Langfuse.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScoreConfigsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ScoreConfigsApi(Langfuse.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScoreConfigsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ScoreConfigsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScoreConfigsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ScoreConfigsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                new Langfuse.Client.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScoreConfigsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ScoreConfigsApi(HttpClient client, Langfuse.Client.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Langfuse.Client.Client.Configuration.MergeConfigurations(
                Langfuse.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Langfuse.Client.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScoreConfigsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ScoreConfigsApi(Langfuse.Client.Client.ISynchronousClient client, Langfuse.Client.Client.IAsynchronousClient asyncClient, Langfuse.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Langfuse.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Langfuse.Client.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Langfuse.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Langfuse.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Langfuse.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Langfuse.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Create a score configuration (config). Score configs are used to define the structure of scores
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateScoreConfigRequest"></param>
        /// <returns>LfScoreConfig</returns>
        public LfScoreConfig ScoreConfigsCreate(LfCreateScoreConfigRequest lfCreateScoreConfigRequest)
        {
            Langfuse.Client.Client.ApiResponse<LfScoreConfig> localVarResponse = ScoreConfigsCreateWithHttpInfo(lfCreateScoreConfigRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create a score configuration (config). Score configs are used to define the structure of scores
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateScoreConfigRequest"></param>
        /// <returns>ApiResponse of LfScoreConfig</returns>
        public Langfuse.Client.Client.ApiResponse<LfScoreConfig> ScoreConfigsCreateWithHttpInfo(LfCreateScoreConfigRequest lfCreateScoreConfigRequest)
        {
            // verify the required parameter 'lfCreateScoreConfigRequest' is set
            if (lfCreateScoreConfigRequest == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'lfCreateScoreConfigRequest' when calling ScoreConfigsApi->ScoreConfigsCreate");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = lfCreateScoreConfigRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LfScoreConfig>("/api/public/score-configs", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScoreConfigsCreate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Create a score configuration (config). Score configs are used to define the structure of scores
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateScoreConfigRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScoreConfig</returns>
        public async System.Threading.Tasks.Task<LfScoreConfig> ScoreConfigsCreateAsync(LfCreateScoreConfigRequest lfCreateScoreConfigRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfScoreConfig> localVarResponse = await ScoreConfigsCreateWithHttpInfoAsync(lfCreateScoreConfigRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Create a score configuration (config). Score configs are used to define the structure of scores
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lfCreateScoreConfigRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScoreConfig)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfScoreConfig>> ScoreConfigsCreateWithHttpInfoAsync(LfCreateScoreConfigRequest lfCreateScoreConfigRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'lfCreateScoreConfigRequest' is set
            if (lfCreateScoreConfigRequest == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'lfCreateScoreConfigRequest' when calling ScoreConfigsApi->ScoreConfigsCreate");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = lfCreateScoreConfigRequest;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<LfScoreConfig>("/api/public/score-configs", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScoreConfigsCreate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get all score configs
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <returns>LfScoreConfigs</returns>
        public LfScoreConfigs ScoreConfigsGet(int? page = default, int? limit = default)
        {
            Langfuse.Client.Client.ApiResponse<LfScoreConfigs> localVarResponse = ScoreConfigsGetWithHttpInfo(page, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all score configs
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <returns>ApiResponse of LfScoreConfigs</returns>
        public Langfuse.Client.Client.ApiResponse<LfScoreConfigs> ScoreConfigsGetWithHttpInfo(int? page = default, int? limit = default)
        {
            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfScoreConfigs>("/api/public/score-configs", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScoreConfigsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get all score configs
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScoreConfigs</returns>
        public async System.Threading.Tasks.Task<LfScoreConfigs> ScoreConfigsGetAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfScoreConfigs> localVarResponse = await ScoreConfigsGetWithHttpInfoAsync(page, limit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all score configs
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number, starts at 1. (optional)</param>
        /// <param name="limit">Limit of items per page. If you encounter api issues due to too large page sizes, try to reduce the limit (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScoreConfigs)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfScoreConfigs>> ScoreConfigsGetWithHttpInfoAsync(int? page = default, int? limit = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Langfuse.Client.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfScoreConfigs>("/api/public/score-configs", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScoreConfigsGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get a score config
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configId">The unique langfuse identifier of a score config</param>
        /// <returns>LfScoreConfig</returns>
        public LfScoreConfig ScoreConfigsGetById(string configId)
        {
            Langfuse.Client.Client.ApiResponse<LfScoreConfig> localVarResponse = ScoreConfigsGetByIdWithHttpInfo(configId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get a score config
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configId">The unique langfuse identifier of a score config</param>
        /// <returns>ApiResponse of LfScoreConfig</returns>
        public Langfuse.Client.Client.ApiResponse<LfScoreConfig> ScoreConfigsGetByIdWithHttpInfo(string configId)
        {
            // verify the required parameter 'configId' is set
            if (configId == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'configId' when calling ScoreConfigsApi->ScoreConfigsGetById");

            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("configId", Langfuse.Client.Client.ClientUtils.ParameterToString(configId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<LfScoreConfig>("/api/public/score-configs/{configId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScoreConfigsGetById", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get a score config
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configId">The unique langfuse identifier of a score config</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LfScoreConfig</returns>
        public async System.Threading.Tasks.Task<LfScoreConfig> ScoreConfigsGetByIdAsync(string configId, System.Threading.CancellationToken cancellationToken = default)
        {
            Langfuse.Client.Client.ApiResponse<LfScoreConfig> localVarResponse = await ScoreConfigsGetByIdWithHttpInfoAsync(configId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get a score config
        /// </summary>
        /// <exception cref="Langfuse.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configId">The unique langfuse identifier of a score config</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LfScoreConfig)</returns>
        public async System.Threading.Tasks.Task<Langfuse.Client.Client.ApiResponse<LfScoreConfig>> ScoreConfigsGetByIdWithHttpInfoAsync(string configId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'configId' is set
            if (configId == null)
                throw new Langfuse.Client.Client.ApiException(400, "Missing required parameter 'configId' when calling ScoreConfigsApi->ScoreConfigsGetById");


            Langfuse.Client.Client.RequestOptions localVarRequestOptions = new Langfuse.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Langfuse.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Langfuse.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("configId", Langfuse.Client.Client.ClientUtils.ParameterToString(configId)); // path parameter

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Langfuse.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LfScoreConfig>("/api/public/score-configs/{configId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ScoreConfigsGetById", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
